### PR TITLE
Added 1080p video quality

### PR DESCRIPTION
**Pull request by NotVinny**
I was receiving a KeyError: '1080p' from line 84 of ServiceCode.pys. I
added the 1080p key to bit_dict, guessed at a bitrate, and it is working
again.

### CODE REVIEW

**Comment by NotVinny** [comment]
(P.S. As I said, I only guessed at the bitrate, so please feel free to check and put the real bitrate in there. I would have but I was having trouble downloading a file to view it's metadata. Also, love your work, all your channels, especially this one. Thanks for your work!)

**Comment by NotVinny** [comment]
(P.P.S. one more thing, this is my first ever pull request so I hope I'm doing it right)

**Comment by Nosinden** [comment]
Thanks for the help.  I don't have time this weekend to check the bitrate, so I'll hold off on merging this till early next week.

**Comment by Nosinden** [comment]
Used `ffprobe -i url` to check bitrates.  Merged you changes and updated the bitrates to reflect what the site host.

Cheers

**Pull request merged**
